services:
  coasterpedia-services:
    image: ghcr.io/coasterpedia/coasterpedia-services/services@${SERVICES_IMAGE}
    restart: always
    networks:
      - coasterpedia_web
    ports:
      - "9004:8080"
    environment:
      CoasterpediaConfig__BaseUrl: http://coasterpedia-mediawiki-1
      ArchiveBotConfig__BotUsername: ArchiveBot
      ArchiveBotConfig__BotPassword: ${ARCHIVE_BOT_PASSWORD}
      FlickrConfig__ApiKey: ${FLICKR_API_KEY}
      CommonsConfig__AccessToken: ${COMMONS_ACCESS_TOKEN}
      GeographConfig__ApiKey: ${GEOGRAPH_API_KEY}
      WikimapiaConfig__ApiKey: ${WIKIMAPIA_API_KEY}
      RedisOptions__ConnectionString: redis:6379
      RedisOptions__Db: 1
networks:
  coasterpedia_web:
    external: true
